# Prefix
set -g prefix C-b
unbind C-b
bind C-b send-prefix

# Splits
# Leader + \  -> vertical split (side by side)
bind '\' split-window -h

# Leader + =  -> horizontal split (top/bottom)
bind '=' split-window -v

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resizing
bind C-h resize-pane -L 5
bind C-j resize-pane -D 5
bind C-k resize-pane -U 5
bind C-l resize-pane -R 5

# General settings
set -g default-shell /bin/zsh
set -g mouse off
set -g history-limit 2000
set -g status on
set -g status-position bottom
set -g status-interval 15

# Status bar
# set -g status-left "[#S] "
# set -g status-left-length 10
# set -g status-right '"#T" %H:%M %d-%b-%y'

# Don't automatically rename windows
set -g allow-rename off
set -g automatic-rename off

# set -g @plugin 'tmux-plugins/tmux-sensible'

# tmux2k (status bar)
set -g @plugin '2kabhishek/tmux2k'

set -g @tmux2k-theme 'catppuccin'

run 'tpack init'
